version: "3"
services: 
  node:
    restart: always
    depends_on: 
      - redis
    build: ./node
    expose: 
      - "3000"
    ports: 
      - "3002:3000"
    networks: 
      - "proxy"
    volumes: 
      - "./Data/node/app:/home/node/app"
    logging: 
      driver: "json-file"
      options: 
        max-size: "1k"

  redis:
    image: redis
    expose: 
      - "6379"
    networks: 
      - "proxy"

networks: 
  proxy:
    driver: bridge


