version: "3"
services: 
  node:
    restart: always
    depends_on: 
      - redis
    build: ./
    expose: 
      - "3000"
    ports: 
      - "3000:3000"
    networks: 
      - "proxy"
    logging: 
      driver: "json-file"
      options: 
        max-size: "100k"

  redis:
    image: redis
    expose: 
      - "6379"
    networks: 
      - "proxy"

networks: 
  proxy:
    driver: bridge


